### ISSUE TITLE
Not sure but Baubles, crashes on server side for 1.15.2

### ISSUE THREAD

**Issue by BedrockLegends** [lazyMods/Baubles#1]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/15/20 1:05 AM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Baubles (baubles) has failed to load correctly
§7null
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.15.0-88-generic
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 2584816416 bytes (2465 MB) / 4187619328 bytes (3993 MB) up to 12562792448 bytes (11980 MB)
	CPUs: 16
	JVM Flags: 31 total; -Xms4G -Xmx12G -XX:PermSize=128m -XX:MaxPermSize=256m -XX:NewRatio=3 -XX:+UseThreadPriorities -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction=1 -XX:SoftRefLRUPolicyMSPerMB=2048 -XX:CMSInitiatingOccupancyFraction=90 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50 -XX:ParallelGCThreads=4 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Xoss4M -Xss4M -XX:UseSSE=4 -XX:+UseLargePages -XX:+UseStringCache -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.19.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.19.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.19.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.19.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.19.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.19
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		upsizer-mc1.15.2-5.1.jar Upsizer {upsizer@5.1.0 CREATE_REGISTRIES}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 CREATE_REGISTRIES}
		ChineseWorkshop-1.15.2-2.4.2.jar ChineseWorkshop {chineseworkshop@2.4.2 CREATE_REGISTRIES}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 CREATE_REGISTRIES}
		Industrial Agriculture[Core]-1.15.2-1.6.6.jar Industrial Agriculture {industrialagriculture@1.15.2-1.6.6 CREATE_REGISTRIES}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 CREATE_REGISTRIES}
		rsgauges-1.15.2-1.2.2-b1.jar Gauges and Switches {rsgauges@1.2.2-b1 CREATE_REGISTRIES}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 CREATE_REGISTRIES}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		dankstorage-2.5.jar Dank Storage {dankstorage@2.5 CREATE_REGISTRIES}
		Powah-1.15.2-1.1.7.jar Powah {powah@1.1.7 CREATE_REGISTRIES}
		ftb-gui-library-1.0.0.14.jar FTB GUI Library {ftbguilibrary@1.0.0.14 CREATE_REGISTRIES}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 CREATE_REGISTRIES}
		ColouredTooltips-1.15.2-6.0.1.jar ColouredTooltips {colouredtooltips@6.0.1 CREATE_REGISTRIES}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.1.4.jar Bookshelf {bookshelf@5.1.4 CREATE_REGISTRIES}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 CREATE_REGISTRIES}
		DarkUtilities-1.15.2-3.0.1.jar Dark Utilities {darkutils@3.0.1 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.0.6.jar Apotheosis {apotheosis@3.0.6 CREATE_REGISTRIES}
		ProgressiveBosses-2.1.4-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.4-mc1.15.2 CREATE_REGISTRIES}
		MekanismGenerators-1.15.2-9.9.15.407.jar Mekanism: Generators {mekanismgenerators@9.9.15 CREATE_REGISTRIES}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 CREATE_REGISTRIES}
		FpsReducer-mc1.15.2-1.14.1.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 CREATE_REGISTRIES}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 CREATE_REGISTRIES}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 CREATE_REGISTRIES}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 CREATE_REGISTRIES}
		Overloaded Compressed Blocks-1.15.2-1.0.12.jar Overloaded Compressed Blocks {overloaded_cb@1.15.2-1.0.10 CREATE_REGISTRIES}
		AmbientSounds_v3.0.17_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.349-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.349 CREATE_REGISTRIES}
		phosphor-mc1.15.2-forge-0.4.2-rc1.jar Phosphor {phosphor@0.4.2-rc1 CREATE_REGISTRIES}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 CREATE_REGISTRIES}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE CREATE_REGISTRIES}
		Lollipop-1.15.2-1.0.9.jar Lollipop {lollipop@1.0.9 CREATE_REGISTRIES}
		fancymain_0.3.1_MC_1.15-1.15.2.jar §dFancy§5Main {fancymain@0.3.1 CREATE_REGISTRIES}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 CREATE_REGISTRIES}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 CREATE_REGISTRIES}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 CREATE_REGISTRIES}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		betbeacpl_1.15.2-1.0.jar Better Beacon Placement {betbeacpl@1.0 CREATE_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 CREATE_REGISTRIES}
		Gobber2-1.15.2-2.2.64.jar Gobber 2 {gobber2@2.2.64 CREATE_REGISTRIES}
		tombstone-4.2.5-1.15.2.jar Corail Tombstone {tombstone@4.2.5 CREATE_REGISTRIES}
		obfuscate-0.3.4-1.15.2.jar Obfuscate {obfuscate@0.3.4 CREATE_REGISTRIES}
		vehicle-mod-0.43.3-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.3 CREATE_REGISTRIES}
		Server Utils-1.15.2-1.1.2.jar Elrol's Server Utilities {serverutilities@1.15.2-1.1.2 CREATE_REGISTRIES}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 CREATE_REGISTRIES}
		cc-tweaked-1.15.2-1.86.2.jar CC: Tweaked {computercraft@1.86.2 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		authme-1.14_1.15-1.1.1.jar Auth Me {authme@1.1.1 CREATE_REGISTRIES}
		BetterBurning-1.15.2-1.3.1.jar BetterBurning {betterburning@1.3.1 CREATE_REGISTRIES}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 CREATE_REGISTRIES}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 CREATE_REGISTRIES}
		PrettyBeaches_1.15.1-4.0.0.jar Pretty Beaches {prettybeaches@4.0.0 CREATE_REGISTRIES}
		SimpleDiscordRichPresence-1.15.2-1.2.4.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.4 CREATE_REGISTRIES}
		SpellChecker-1.15-1.0.3.1.jar Spell Checker {spellchecker@1.0.3.1 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.1.11.jar Cyclic {cyclic@1.15.2-0.1.11 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.7.0.jar Kiwi {kiwi@2.7.0 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 CREATE_REGISTRIES}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 CREATE_REGISTRIES}
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 CREATE_REGISTRIES}
		creeperfix-1.15.2-1.3.jar CreeperFix {creeperfix@1.3 CREATE_REGISTRIES}
		snad-1.8.4.22a-1.15.2.jar Snad {snad@1.8.3.3a CREATE_REGISTRIES}
		item-filters-2.2.0.14.jar Item Filters {itemfilters@2.2.0.14 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 CREATE_REGISTRIES}
		lithium-mc1.15.2-forge-0.4.5-rc2-mod.jar Lithium {lithium@0.4.5-rc2 CREATE_REGISTRIES}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 CREATE_REGISTRIES}
		Mekanism-1.15.2-9.9.15.407.jar Mekanism {mekanism@9.9.15 CREATE_REGISTRIES}
		invtweaks-1.15.2-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 CREATE_REGISTRIES}
		LightOverlay-4.3.jar Light Overlay Forge {lightoverlay-forge@4.3 CREATE_REGISTRIES}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		SimpleStorageNetwork-1.15.2-0.2.4.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 CREATE_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 CREATE_REGISTRIES}
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 CREATE_REGISTRIES}
		FarmingForBlockheads_1.15.2-6.1.0.jar Farming for Blockheads {farmingforblockheads@6.1.0 CREATE_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 CREATE_REGISTRIES}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha CREATE_REGISTRIES}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha CREATE_REGISTRIES}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha CREATE_REGISTRIES}
		rftoolsstorage-1.15-1.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.2-alpha CREATE_REGISTRIES}
		ClickMachine-1.15.2-3.0.1.jar Click Machine {clickmachine@3.0.1 CREATE_REGISTRIES}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 CREATE_REGISTRIES}
		mininggadgets-1.3.1.jar Mining Gadgets {mininggadgets@1.3.1 CREATE_REGISTRIES}
		immersive-portals-0.6(for mc 1.15 with forge).jar Immersive Portals {immersive_portals@0.6 CREATE_REGISTRIES}
		CraftTweaker-1.15.2-6.0.0.9.jar CraftTweaker {crafttweaker@6.0.0.9 CREATE_REGISTRIES}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha CREATE_REGISTRIES}
		ftb-chunks-1.0.0.1.jar FTB Chunks {ftbchunks@1.0.0.1 CREATE_REGISTRIES}
		forge-1.15.2-31.1.19-universal.jar Forge {forge@31.1.19 CREATE_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 CREATE_REGISTRIES}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 CREATE_REGISTRIES}
		forge-1.15.2-31.1.19-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b CREATE_REGISTRIES}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha CREATE_REGISTRIES}
		EnchantmentDescriptions-1.15.2-2.0.3.jar EnchantmentDescriptions {enchdesc@2.0.3 CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 CREATE_REGISTRIES}
		bspawncontrol_1.15.2-1.0.jar Better Spawner Control {bspawncontrol@1.0 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 CREATE_REGISTRIES}
		ftb-quests-2.0.2.244.jar FTB Quests {ftbquests@2.0.2.244 CREATE_REGISTRIES}
		baubles-1.7.0-1.15.2.jar Baubles {baubles@1.6.0 ERROR}
		ceramicbucket-1.1.0-1.14.4_1.15.X.jar Ceramic Bucket {ceramicbucket@1.1.0-1.14.4_1.15.X CREATE_REGISTRIES}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha CREATE_REGISTRIES}
		Industrial Agriculture[Omega Craft]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Omega Craft {iapoc@1.15.2-1.6.1 CREATE_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 CREATE_REGISTRIES}
		AutoRegLib-1.5-37.jar AutoRegLib {autoreglib@1.5-37 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 CREATE_REGISTRIES}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 CREATE_REGISTRIES}
		performant-1.15-1.7.jar Performant {performant@1.7 CREATE_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		engineersdecor-1.15.2-1.0.20-b1.jar Engineer's Decor {engineersdecor@1.0.20-b1 CREATE_REGISTRIES}
		solcarrot-1.15.2-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.15.2-1.9.4 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 CREATE_REGISTRIES}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 CREATE_REGISTRIES}
		waterworks-1.15.2-2.1.1.jar Waterworks {waterworks@1.15.2-2.1.1 CREATE_REGISTRIES}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 CREATE_REGISTRIES}
		CraftingCraft_1.15.1-8.0.0.jar CraftingCraft {craftingcraft@8.0.0 CREATE_REGISTRIES}
		Omega Craft 4.0.9 - 1.15.2.jar Omega Craft {omegacraft@1.0 CREATE_REGISTRIES}
		Mubble-3.0.2-(Forge-1.15.2).jar Mubble {mubble@3.0.2 CREATE_REGISTRIES}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by lazynessmind** [comment]
Thanks for the report. the new version has been upload to curse.
