### ISSUE TITLE
Question about data-driven baubles

### ISSUE THREAD

**Issue by vico93** [lazyMods/Baubles#10]
Where exact in the datapack should i store the .json?

In the comment of the json file on gist it says it should go in a baubles folder, that would be directly under `data`? or in the modid/datapack prefix `data\whatevermod\baubles`?

Thanks for any clarification

**Comment by lazynessmind** [comment]
Hi. The baubles folder should be in the game folder. Normally if you run vanilla minecraft the game folder is . minecraft.

To be more clear _.minecraft/baubles/nameoffile.json_

In some cases like Twitch launcher the game folder is saved in other directory. In that case you find the directory and add another folder called baubles

**Comment by vico93** [comment]
Oh, i thought it was loadable by datapacks.
