### ISSUE TITLE
1.16.5 NPE - client side crash

### ISSUE THREAD

**Issue by kreezxil** [lazyMods/Baubles#16]
We have journeymap installed too. When players press 'B' to make a bookmark on journeymap, this crash happens to them.

https://gist.githubusercontent.com/natanfudge/073dc37a307e8180b2f2fe5f6286fe2e/raw/a1d8bf8eb2837dbf501596d8e94b0beb18354d68/crash.txt

**Comment by kreezxil** [comment]
Mod version: 1.8.7.1-1.16.5
Forge version: 36.1.35
MC version: 1.16.5

**Comment by lazynessmind** [comment]
Fixing it...

**Comment by lazynessmind** [comment]
Can't reproduce the issue using the same present in your log.

JourneyMap - 1.16.5-5.7.2beta18
Baubles - 1.8.7.1
Forge-36.1.35

![image](https://user-images.githubusercontent.com/52864251/126041385-d118a23d-c80c-4649-91dc-fedc0ba819ac.png)

**Comment by lazynessmind** [comment]
[baubles-may-fix-1.8.7.2.zip](https://github.com/lazyMods/baubles/files/6834949/baubles-may-fix-1.8.7.2.zip)

# Github don't let you upload .jar files, so extract this and check if it fixes the bug

**Comment by kreezxil** [comment]
will do. thanks.

**Comment by kreezxil** [comment]
alright, i loaded up, hit 'b' and crashed with that version you said to try. https://gist.githubusercontent.com/natanfudge/9989fe2b47e5fdee0a659fe4193fbece/raw/ee029ada99e07251586e4bd54b4df7cc9ab71408/crash.txt

It might be an issue the backpack mod we're using, we've also discovered that remapping the 'b' key stops the crash.

**Comment by lazynessmind** [comment]
Hmm, can you send me the modpack link?

**Comment by kreezxil** [comment]
It's a pack i have in alpha testing not yet released. Here is the current
link to the alpha build.
https://drive.google.com/file/d/1Zi4o5xK5tRe4RQJ7ji594ann13-7voNq/view?usp=drivesdk,
I rolled back to the previous official version since your patch made no
difference.

**Comment by lazynessmind** [comment]
did the backpack mod fix the error?

**Comment by kreezxil** [comment]
Backpack? Hmm. Not sure where you got that from in this ticket. But yes, I'll close this because the issue hasn't come back up. Seems maybe there was a mod conflict. I still got your mod in the pack, and it's rolling fine.

![image](https://user-images.githubusercontent.com/3880072/129372249-7e8560ff-c587-450b-bad0-c6c3cb287187.png)

I update this test pack at least 20 times since this report. :)

**Comment by lazynessmind** [comment]
:+1:
