### ISSUE TITLE
Render Error on newest build when used in IDE

### ISSUE THREAD

**Issue by JayDo96** [lazyMods/Baubles#17]
Im getting a render error when attempting to launch the game with this mod installed. Id like to get this figured out so I can work on a mod using the API.
[crash-2021-09-21_06.55.37-client.txt](https://github.com/lazyMods/baubles/files/7202541/crash-2021-09-21_06.55.37-client.txt)

**Comment by lazynessmind** [comment]
Fixing it.

**Comment by Aaronstar-McClure** [comment]
im still getting a similar issue as this when trying to load the 1.16.5 version in ide. i have tried both 1.8.7 and 1.8.7.1. was this fix applied to the 1.16 tree?

`net.minecraftforge.fml.ModLoadingException: Baubles (baubles) encountered an error during the sided_setup event phase
java.lang.NoSuchMethodError: net.minecraft.client.renderer.texture.AtlasTexture.func_229223_g_()Lnet/minecraft/util/ResourceLocation;
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:124) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$34(ModLoader.java:326) ~[forge:?] {re:classloading}`

**Comment by Aaronstar-McClure** [comment]
to anyone who may have this problem in the future, i was able to resolve this issue.

originally i had in my build.gradle
`implementation 'com.github.lazyMods:baubles:1.8.7-1.16.5'`

instead i now use
`compileOnly fg.deobf('com.github.lazyMods:baubles:1.8.7.1-1.16.5')` 
`runtimeOnly fg.deobf('com.github.lazyMods:baubles:1.8.7.1-1.16.5')`

i dont know why this works, or why it didnt work before, but i can still reference baubles code is source, and baubles successfully loads in runclient
