### ISSUE TITLE
My game crash on dev env when I try to open the inventory

### ISSUE THREAD

**Issue by grillo78** [lazyMods/Baubles#2]
[latest.log](https://github.com/lazyMods/Baubles/files/4343354/latest.log)
I'm trying to do a baubles item but when I open the inventory my game crash, I tried to comment the code related to baubles and is the same

**Comment by lazynessmind** [comment]
Hmm, I can´t see why this is related to Baubles. Are you using IRenderBauble?

**Comment by grillo78** [comment]
No, this happen after add Baubles to the dev env

**Comment by lazynessmind** [comment]
Hummm. The problem is that on the log I cant see anything related to the Baubles Mod. How are you using the api or the dev.jar?

**Comment by grillo78** [comment]
sorry for the late reply, I couldn't enter to github yesterday, this is my build.gradle
(https://github.com/grillo78/BeyCraft/blob/master/build.gradle)

**Comment by lazynessmind** [comment]
Hmm. I'm at work now, could you try use the API jar instead on the release tab? Probably the jitpack.io jar isnt building properly. I need to test it when I arrive at home

**Comment by grillo78** [comment]
okay, I'll test

**Comment by grillo78** [comment]
I was able to do it with the deobf, for some reason the API doesn't load as library in IntelliJ

**Comment by lazynessmind** [comment]
Oh, thats weird

**Comment by J-Dill** [comment]
For anyone else that runs into this problem in the future, this is how I ended up getting the Baubles dependency to work:
`compile fg.deobf('com.github.lazyMods:Baubles:1.15.2-SNAPSHOT')`

**Comment by lazynessmind** [comment]
> 
> 
> For anyone else that runs into this problem in the future, this is how I ended up getting the Baubles dependency to work:
> `compile fg.deobf('com.github.lazyMods:Baubles:1.15.2-SNAPSHOT')`

Thanks!
