### ISSUE TITLE
Crash with Forge 33.0.22

### ISSUE THREAD

**Issue by cech12** [lazyMods/Baubles#6]
Game crashes at world joining when this Mod is installed.

Minecraft 1.16.2
Forge 33.0.22

[latest.log](https://github.com/lazyMods/Baubles/files/5135817/latest.log)

**Comment by lazynessmind** [comment]
Baubles currently is using Forge 33.0.5. Updating soon.

**Comment by lazynessmind** [comment]
Fixed in commit 3cafc69
