### ISSUE TITLE
[1.16] Cannot start in development environment

### ISSUE THREAD

**Issue by cech12** [lazyMods/Baubles#7]
I wanted to support your mod. At first I tried to import your mod via gradle. Here is my code for this:

```
repositories {
    maven {
        name 'Baubles'
        url 'https://jitpack.io'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:1.16.2-33.0.5"
    compile "com.github.lazyMods:Baubles:1.8.0"
}
```
When I start the development environment an error occurs at startup: [latest.log](https://github.com/lazyMods/Baubles/files/5219520/latest.log)
I am using the same forge mapping as you do: "20200514-1.16"

Unfortunately "com.github.lazyMods:Baubles:1.8.1" is not available to test a later version.

What am I doing wrong?

**Comment by cech12** [comment]
Same for 1.15: [latest.log](https://github.com/lazyMods/Baubles/files/5219603/latest.log)
And for 1.14: [latest.log](https://github.com/lazyMods/Baubles/files/5219619/latest.log)

**Comment by Brzjomo** [comment]
YES! The same problem.

NoSuchMethodError: net.minecraft.client.gui.ScreenManager.func_216911_a(Lnet/minecraft/inventory/container/ContainerType;Lnet/minecraft/client/gui/ScreenManager$IScreenFactory

--------------------
Actually i develop with the given api and use the released file on curseforge to test my mod. Now i can't directly run client in the dev tool, i have to build my mod first and test it with baubles in another folder. 
It's not perfect but it works.

**Comment by cech12** [comment]
This is also the workaround I use for this. But it does not fix the problem ;)
I use `compileOnly` instead of `compile` to run the mod in test environment. But then Baubles is not included to it. Baubles is only an optional dependency for my mod. If your mod depend on Baubles, this would not work xD

**Comment by lazynessmind** [comment]
Sorry for the late reply. Currently, Baubles is using 33.0.22 and you are trying to compile it with 33.0.5. That's the problem. Today (27/09/2020) I'm going to update it to 1.16.3. When this new release is out, try again.

**Comment by lazynessmind** [comment]
Check out the new release (1.8.2) and reopen the issue if the problem persists.
